name: Check HTTP Response Status

on:
  push:
    branches:
      - master

jobs:
  check_post_request:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST Request and Check Status
        run: |
          response=$(curl --max-time 30 -o /dev/null -s -w "%{http_code}" -X POST http://192.168.11.2/job/build_test/build?token=mysecrettoken)
          echo "HTTP status: $response"
        shell: /usr/bin/bash -e
